Add Czech Translation
codeigniter4/shield pull request #1012
Opened 2024-02-02 00:52 UTC by MichalSkoula

I have added Czech translation for shield + fixed Slovak translation.

2024-02-02 08:31 UTC, kenjis requested changes
Please don't include [sk] changes in a [cs] PR.

2024-02-02 12:25 UTC, MichalSkoula commented
Ok I have reverted Slovak translation with a new commit.

2024-02-02 12:27 UTC, datamweb commented
Hi,
Thank you for contributing!
Please see https://github.com/codeigniter4/shield/pull/235#issuecomment-1153050805

2024-02-02 12:39 UTC, MichalSkoula commented
ok done :)

2024-02-02 12:49 UTC, datamweb requested changes

2024-02-02 12:49 UTC, datamweb commented on src/Language/cs/Auth.php
> +    'errorPasswordLength'       => 'Heslo musí mít alespoň {0, číslo} znaků.',
```suggestion
    'errorPasswordLength'       => 'Heslo musí mít alespoň {0, number} znaků.',
```

2024-02-02 12:49 UTC, datamweb commented on src/Language/cs/Auth.php
> +    'errorPasswordPwned'        => 'Heslo {0} bylo odhaleno v důsledku úniku dat a bylo zaznamenáno {1, počet}krát z {2} prolomených hesel.',
```suggestion
    'errorPasswordPwned'        => 'Heslo {0} bylo odhaleno v důsledku úniku dat a bylo zaznamenáno {1, number} krát z {2} prolomených hesel.',
```

2024-02-02 12:49 UTC, datamweb commented on tests/Language/CzechTranslationTest.php
> +{
```suggestion
{
    protected array $excludedLocaleKeyTranslations = [
        'Auth.token',
    ];
```

2024-02-02 12:53 UTC, datamweb commented on src/Language/cs/Auth.php
> +    'token'           => '(To be translated) Token',
```suggestion
    'token'           => 'Token',
```

2024-02-02 13:02 UTC, datamweb approved these changes
LGTM!
thank you!

2024-02-03 00:58 UTC, kenjis approved these changes

2024-02-03 10:07 UTC, datamweb commented
@MichalSkoula See https://github.com/codeigniter4/shield/pull/672#issuecomment-1468658726

2024-02-03 11:01 UTC, MichalSkoula commented
> @MichalSkoula See [#672 (comment)](https://github.com/codeigniter4/shield/pull/672#issuecomment-1468658726)

Should I create a new PR?

2024-02-03 11:12 UTC, datamweb commented
How to sign past commits is explained [here](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#gpg-signing-old-commits), but feel free to do so if you're comfortable creating new PRs.

2024-02-03 19:35 UTC, MichalSkoula commented
Creating a new PR is easier for me. I have done so - https://github.com/codeigniter4/shield/pull/1015

2024-02-03 19:35 UTC, closed without merging