change hardcoded user entity with declared return type
codeigniter4/shield pull request #1105
Opened 2024-04-23 11:35 UTC by MrFrost-Nv27

**Description**
Fixes #1104 

**Checklist:**
- [ ] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

2024-04-24 03:40 UTC, datamweb approved these changes

2024-04-25 01:13 UTC, kenjis approved these changes

2024-04-25 01:17 UTC, kenjis commented
If a dev extends the UserModel and changed `$returnType`, it returns incorrect `CodeIgniter\Shield\Entities\User` instances. So I think this is a bug.

2024-04-25 01:28 UTC, MrFrost-Nv27 commented
> If a dev extends the UserModel and changed `$returnType`, it returns incorrect `CodeIgniter\Shield\Entities\User` instances. So I think this is a bug.

Yes that what i mean .. i want customize the User entity, but still extend Shield User entity base class

2024-04-25 01:30 UTC, paulbalandan requested changes
This will fail if you changed the return type to `array`, right?

2024-04-25 01:35 UTC, MrFrost-Nv27 commented
> This will fail if you changed the return type to `array`, right?

Based on method type, yes ...because it must return User class .. its no problem to change the returntype but still extend the base user entity class

2024-04-25 02:40 UTC, kenjis commented
@paulbalandan What do you want?
`array` is not allowed because User Provider must return `User` entities.

2024-04-25 05:11 UTC, paulbalandan commented
Let me rephrase:

For the longest time, it has been `User` to be the return type. Now, this PR will change the return to be what is defined in `$returnType` and we are blindly instantiating whatever its value. So, in essence, anyone can put other return types, right? So, if a dev puts `'array'` as return type, the `fake()` method will instantiate an "`array` class". If another dev puts their own Entity subclass which does extend `User`, the faking will throw a TypeError.

What I am saying is since `UserProvider` expects `User` entities, we must make sure that `$returnType` should follow this now that we have lax requirement.

2024-04-25 05:27 UTC, MrFrost-Nv27 commented
> Let me rephrase:
> 
> For the longest time, it has been `User` to be the return type. Now, this PR will change the return to be what is defined in `$returnType` and we are blindly instantiating whatever its value. So, in essence, anyone can put other return types, right? So, if a dev puts `'array'` as return type, the `fake()` method will instantiate an "`array` class". If another dev puts their own Entity subclass which does extend `User`, the faking will throw a TypeError.
> 
> What I am saying is since `UserProvider` expects `User` entities, we must make sure that `$returnType` should follow this now that we have lax requirement.

Yes bro, but in fake() method for example, there is a declarative return type that was make sure the method is returning declared type, is User class, if some dev change the model $returnType to array, there was an error of "typeError" before the array return

2024-04-25 05:54 UTC, kenjis commented
@paulbalandan 
>  So, in essence, anyone can put other return types, right? 

No. If a dev puts `array` or class-string other than `User` (or a sub class), `UserModel` does not work due to a TypeError, as @MrFrost-Nv27 says.

2024-05-02 17:41 UTC, paulbalandan reviewed
Sorry to not have seen the comments earlier and dragging this along.

I am well aware that it will throw a `TypeError` if you put other return types there. I even put that remark in my comment. I am just saying that we must be at least prudent in checking the value of `$returnType` before instantiating the value. I want to see something along the lines of:
```php
if (! is_a($this->returnType, User::class, true) {
    throw new \LogicException('Return type must be a subclass of CodeIgniter\Shield\Entities\User.');
}
```

As an end user who may be new to Shield, for example, I don't want to be greeted by a `TypeError`  with message "Return value of fake must return User but returns other class."when faking data. I think it will be a better developer experience if the thrown exception is more informational of the requirement.

I hope I made myself clear.

2024-05-02 21:12 UTC, MrFrost-Nv27 commented
> Sorry to not have seen the comments earlier and dragging this along.
> 
> I am well aware that it will throw a `TypeError` if you put other return types there. I even put that remark in my comment. I am just saying that we must be at least prudent in checking the value of `$returnType` before instantiating the value. I want to see something along the lines of:
> ```php
> if (! is_a($this->returnType, User::class, true) {
>     throw new \LogicException('Return type must be a subclass of CodeIgniter\Shield\Entities\User.');
> }
> ```
> 
> As an end user who may be new to Shield, for example, I don't want to be greeted by a `TypeError`  with message "Return value of fake must return User but returns other class."when faking data. I think it will be a better developer experience if the thrown exception is more informational of the requirement.
> 
> I hope I made myself clear.

Yeah not bad to implement that

2024-05-02 21:43 UTC, kenjis commented
@paulbalandan I don't know how useful that error message would be.
 But it would be a little easier to understand than PHP's TypeError.

Changing the error message that way is fine.

2024-05-02 21:52 UTC, kenjis commented
@MrFrost-Nv27 `User::$id` can be a string. 
https://github.com/codeigniter4/shield/blob/db10ec1cdaf16ad99150ae4b88c6839c11f19b41/src/Entities/User.php#L30

If you cannot use a string, it is another bug.
So please create a new issue. I hope you complete this PR.

2024-05-02 21:55 UTC, MrFrost-Nv27 reviewed
ok

2024-05-02 22:16 UTC, MrFrost-Nv27 commented
> @MrFrost-Nv27 `User::$id` can be a string.
> 
> https://github.com/codeigniter4/shield/blob/db10ec1cdaf16ad99150ae4b88c6839c11f19b41/src/Entities/User.php#L30
> 
> If you cannot use a string, it is another bug. So please create a new issue. I hope you complete this PR.
> 
> By the way, what do you mean by "wkwk"?

is just "a laugh in chat" in my country

2024-05-02 23:32 UTC, kenjis commented
@MrFrost-Nv27 Oh, you are correct. Because of #336

2024-05-02 23:46 UTC, MrFrost-Nv27 commented
> @MrFrost-Nv27 Oh, you are correct. Because of #336
> 

Yeah, so i think i just want customize the User Entity in my side, not in base side .. and ensure my customize entities work in base flow ..

2024-05-02 23:51 UTC, kenjis commented on src/Models/UserModel.php
> +            }
Don't repeat the same check.
Create a private method for it.

2024-05-02 23:55 UTC, kenjis commented on src/Models/UserModel.php
> +use LogicException;
```suggestion
use CodeIgniter\Shield\Exceptions\LogicException;
```
and run `composer cs-fix`.

2024-05-02 23:57 UTC, kenjis commented
Please sign all your commits.
![Screenshot 2024-05-03 8 55 46](https://github.com/codeigniter4/shield/assets/87955/af8201d1-bf65-415d-bf17-cc47c9c42cb4)
See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/signing.md#gpg-signing-old-commits

2024-05-03 17:41 UTC, paulbalandan approved these changes
Thanks for the changes!

Based on your requirement to use UUIDs in $id, I think extending User would be the best solution, to say the least.

2024-05-04 09:30 UTC, merged

2024-05-04 09:30 UTC, kenjis commented
@MrFrost-Nv27 Thank you!