Polish translation
codeigniter4/shield pull request #1117
Opened 2024-05-12 23:02 UTC by mieszkou

I added a Polish translation of the texts

2024-05-12 23:07 UTC, datamweb commented
Hi,
Thank you for contributing!
Please see https://github.com/codeigniter4/shield/pull/235#issuecomment-1153050805

2024-05-13 12:49 UTC, michalsn requested changes

2024-05-13 12:49 UTC, michalsn commented on src/Language/pl/Auth.php
> +    'badAttempt'            => 'Nie można cię zalogować. Sprawdź swoje poświadczenia.',
```suggestion
    'badAttempt'            => 'Nie można Cię zalogować. Sprawdź swoje dane uwierzytelniające.',
```

2024-05-13 12:49 UTC, michalsn commented on src/Language/pl/Auth.php
> +    'invalidPassword'       => 'Nie można cię zalogować. Sprawdź hasło.',
```suggestion
    'invalidPassword'       => 'Nie można cię zalogować. Sprawdź swoje hasło.',
```

2024-05-13 12:49 UTC, michalsn commented on src/Language/pl/Auth.php
> +    'invalidEmail'          => 'Nie można zweryfikować adresu e -mail odpowiada e -maile w rekordach.',
```suggestion
    'invalidEmail'          => 'Nie można zweryfikować zgodności adresu e-mail z zarejestrowanym adresem e-mail.',
```

2024-05-13 12:49 UTC, michalsn commented on src/Language/pl/Auth.php
> +    'unableSendEmailToUser' => 'Przepraszam, był problem z wysłaniem wiadomości e -mail. Nie mogliśmy wysłać wiadomości e -mail do "{0}".',
```suggestion
    'unableSendEmailToUser' => 'Przepraszamy, był problem z wysłaniem wiadomości e-mail. Nie mogliśmy wysłać wiadomości e-mail do "{0}".',
```

2024-05-13 12:49 UTC, michalsn commented on src/Language/pl/Auth.php
> +    'throttled'             => 'Zbyt wiele żądań złożonych z tego adresu IP. Możesz spróbować ponownie za {0} sekundy.',
```suggestion
    'throttled'             => 'Zbyt wiele żądań z tego adresu IP. Możesz spróbować ponownie za {0} sekund.',
```

2024-05-13 12:49 UTC, michalsn commented on src/Language/pl/Auth.php
> +    'notEnoughPrivilege'    => 'Nie masz niezbędnego pozwolenia na wykonanie pożądanej operacji.',
```suggestion
    'notEnoughPrivilege'    => 'Nie masz uprawnień niezbędnych do wykonania żądanej operacji.',
```

2024-05-13 12:49 UTC, michalsn commented on src/Language/pl/Auth.php
> +    'email'           => 'Adres e -mail',
```suggestion
    'email'           => 'Adres e-mail',
```

2024-05-13 12:49 UTC, michalsn commented on src/Language/pl/Auth.php
> +    'checkYourEmail'     => 'Sprawdź swój email!',
```suggestion
    'checkYourEmail'     => 'Sprawdź swój e-mail!',
```

2024-05-13 12:49 UTC, michalsn commented on src/Language/pl/Auth.php
> +    'magicLinkExpired'   => 'Przepraszam, link wygasł.',
```suggestion
    'magicLinkExpired'   => 'Przepraszamy, link wygasł.',
```

2024-05-13 12:49 UTC, michalsn commented on src/Language/pl/Auth.php
> +    'magicLinkDetails'   => 'Właśnie wysłaliśmy Ci wiadomość e-mail z linkiem logowania w środku. Jest on ważny tylko {0} minut.',
```suggestion
    'magicLinkDetails'   => 'Właśnie wysłaliśmy do Ciebie wiadomość e-mail z linkiem do logowania. Jest on ważny tylko {0} minut.',
```

2024-05-13 12:49 UTC, michalsn commented on src/Language/pl/Auth.php
> +    'successLogout'      => 'Udało Ci się wylogować.',
```suggestion
    'successLogout'      => 'Wylogowanie powiodło się.',
```

2024-05-13 12:49 UTC, michalsn commented on src/Language/pl/Auth.php
> +    'suggestPasswordCommon'     => 'Hasło sprawdzono na ponad 65 000 powszechnie używanych haseł lub haseł, które zostały wyciekane przez hacki.',
```suggestion
    'suggestPasswordCommon'     => 'Hasło zostało porównane z ponad 65 tysiącami powszechnie używanych haseł lub haseł, które wyciekły w wyniku włamania.',
```

2024-05-13 12:49 UTC, michalsn commented on src/Language/pl/Auth.php
> +    'suggestPasswordPersonal'   => 'Odmiany twojego adresu e -mail lub nazwy użytkownika nie powinny być używane do haseł.',
```suggestion
    'suggestPasswordPersonal'   => 'W hasłach nie należy stosować odmian adresu e-mail lub nazwy użytkownika.',
```

2024-05-13 12:49 UTC, michalsn commented on src/Language/pl/Auth.php
> +    'passwordChangeSuccess'     => 'Hasło zmieniło się pomyślnie',
```suggestion
    'passwordChangeSuccess'     => 'Hasło zostało pomyślnie zmienione',
```

2024-05-13 12:49 UTC, michalsn commented on src/Language/pl/Auth.php
> +    'userDoesNotExist'          => 'Hasło nie zostało zmienione.użytkownik nie istnieje',
```suggestion
    'userDoesNotExist'          => 'Hasło nie zostało zmienione. Użytkownik nie istnieje',
```

2024-05-13 12:49 UTC, michalsn commented on src/Language/pl/Auth.php
> +    'resetTokenExpired'         => 'Przepraszam. Twój token resetowania wygasł.',
```suggestion
    'resetTokenExpired'         => 'Przepraszamy. Twój token resetowania wygasł.',
```

2024-05-13 12:49 UTC, michalsn commented on src/Language/pl/Auth.php
> +    'emailEnterCode'      => 'Potwierdź swój email',
```suggestion
    'emailEnterCode'      => 'Potwierdź swój e-mail',
```

2024-05-13 12:49 UTC, michalsn commented on src/Language/pl/Auth.php
> +    'email2FAMailBody'    => 'Twój kod uwierzytelnienia jest:',
```suggestion
    'email2FAMailBody'    => 'Twój kod uwierzytelnienia to:',
```

2024-05-13 12:49 UTC, michalsn commented on src/Language/pl/Auth.php
> +    'emailActivateTitle'    => 'Aktywacja e-maila',
```suggestion
    'emailActivateTitle'    => 'Aktywacja e-mail',
```

2024-05-13 12:49 UTC, michalsn commented on src/Language/pl/Auth.php
> +    'emailActivateBody'     => 'Właśnie wysłaliśmy do Ciebie wiadomość e -mail z kodem, aby potwierdzić Twój adres e -mail.Skopiuj ten kod i wklej go poniżej.',
```suggestion
    'emailActivateBody'     => 'Właśnie wysłaliśmy do Ciebie wiadomość e-mail z kodem potwierdzającym Twój adres e-mail. Skopiuj ten kod i wklej go poniżej.',
```

2024-05-13 12:49 UTC, michalsn commented on src/Language/pl/Auth.php
> +    'unknownPermission' => '{0} nie jest ważnym pozwoleniem.',
```suggestion
    'unknownPermission' => '{0} nie jest ważnym uprawnieniem.',
```

2024-05-14 00:17 UTC, kenjis commented
Please fix the following failure.

```
There was 1 failure:

1) Tests\Language\PolishTranslationTest::testAllIncludedLanguageKeysAreTranslated with data set "pl" ('pl')
Failed asserting that the translated language key "Auth.token" in "pl" locale differs from the original keys in the main repository.
Failed asserting that an array is empty.

/home/runner/work/shield/shield/tests/Language/AbstractTranslationTestCase.php:259
```
https://github.com/codeigniter4/shield/actions/runs/9068936216/job/24922062972?pr=1117

2024-05-14 00:20 UTC, kenjis commented on src/Language/pl/Auth.php
> +    'token'           => 'Token',
If the translation is correct, add `$excludedLocaleKeyTranslations` in the test case class.
See https://github.com/codeigniter4/shield/pull/913#issuecomment-1766414597

2024-05-14 00:24 UTC, kenjis commented
Also, please sign all commits.
See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#signing
https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#gpg-signing-old-commits

2024-05-18 15:51 UTC, datamweb commented
@mieszkou thank you! 
The last thing to do is to sign all the commits.

![Screenshot 2024-05-18 191831](https://github.com/codeigniter4/shield/assets/9530214/651035ca-9f16-4b44-a67b-20b5a813e7d3)

It is explained [gpg-signing-old-commits](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#gpg-signing-old-commits).

As a faster alternative, you can still securely sign commits without the `-S` option in git commit. See [Set Default Signing](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/signing.md#set-default-signing).

2024-05-19 00:09 UTC, datamweb approved these changes

2024-05-19 00:43 UTC, kenjis approved these changes
Thank you!

2024-05-19 06:00 UTC, michalsn approved these changes
Nice work!

2024-05-19 06:07 UTC, merged

2024-05-19 06:07 UTC, datamweb commented
@mieszkou Welcome to Shield Contributors!
 Merged.