Updated email templates with user information
codeigniter4/shield pull request #1125
Opened 2024-06-07 03:05 UTC by pmagictech

**Description**
This pull request enhances the existing email templates by including the username of the recipient. This update aims to improve the personalization of the emails, making the communication more engaging and user-friendly. By making the User Entity object accessible in the email templates, Shield users can now easily add user-specific details, tailoring the emails to better suit their needs.

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

2024-06-13 02:23 UTC, kenjis commented
Thank you for sending this PR.

We don't accept PRs without test code that proves the change works properly.
Please add test code.
See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#unit-testing

2024-06-13 06:17 UTC, datamweb requested changes
Thanks for PR.
You can get help from [Email Test](https://github.com/codeigniter4/shield/blob/aa40f9c121d9619470c743afc99426c2d29477a5/tests/Controllers/ActionsTest.php#L232-L251) for write the test.

2024-06-13 06:17 UTC, datamweb commented on src/Views/Email/email_2fa_email.php
> +</html>
Please use `LF` NOT `CRLF`.
See more information [understanding-line-break-types](https://dev.to/pranjal-barnwal/understanding-line-break-types-cr-lf-lf-and-cr-3lg2).

2024-06-13 06:17 UTC, datamweb commented on src/Views/Email/magic_link_email.php
> +</html>
Please use `LF` NOT `CRLF`.
See more information [understanding-line-break-types](https://dev.to/pranjal-barnwal/understanding-line-break-types-cr-lf-lf-and-cr-3lg2).

2024-06-13 12:02 UTC, datamweb reviewed
Can you update description  https://github.com/codeigniter4/shield/blob/develop/docs/customization/views.md#customize-content and explain that user data(User Entity object) in email tpls is now available?

2024-06-13 14:07 UTC, datamweb approved these changes
LGTM🫡!

2024-06-15 01:08 UTC, kenjis approved these changes

2024-06-15 01:09 UTC, merged

2024-06-15 01:09 UTC, kenjis commented
@pmagictech Thank you!

2024-06-15 04:15 UTC, pmagictech commented
@kenjis You are welcome