feat: Add expiration date to access token & hmac keys
codeigniter4/shield pull request #1219
Opened 2024-11-03 22:54 UTC by CosDiabos

**Description**
Implements custom date expiration for Access Tokens and Hmac Keys/tokens leveraging the `expires` column within auth_identities table. 

Implements `setAccessTokenExpirationById()` method, getAccessTokenTimeToExpire(), hasHmacTokenExpired() trait methods and the CLI command `shield:hmac invalidateAll`.

Implements #926 

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [x] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

2025-02-10 11:48 UTC, michalsn reviewed
Sorry you had to wait so long for feedback.

The PR looks nice, although I have questions about the reasons for some of the "implementation" choices.

2025-02-10 11:48 UTC, michalsn commented on src/Authentication/Traits/HasAccessTokens.php
> +    public function generateAccessToken(string $name, array $scopes = ['*'], ?string $expiresAt = null): AccessToken
The type chosen for `$expiresAt` is quite strange to me - why `?string` and not `?Time`?
`Time` seems a lot more universal and we wouldn't need `checkExpiresAtFormat()` method at all.

2025-02-10 11:48 UTC, michalsn commented on src/Authentication/Traits/HasAccessTokens.php
> +    public function getAccessTokenTimeToExpire(?AccessToken $accessToken, string $format = 'date'): string|null
Relying directly on the `Time` object seems more universal to me. Let the developers decide what format they want to display the expiration date in. I would get rid of this method.

2025-02-10 11:48 UTC, michalsn commented on src/Authentication/Traits/HasAccessTokens.php
> +    public function hasAccessTokenExpired(?AccessToken $accessToken): bool|null
Can we return here only `true`/`false` - this seems more appropriate.

We can introduce another method, like `canAccessTokenExpire()` to determine whether the token has an expiration date.

2025-02-13 14:24 UTC, CosDiabos commented on src/Authentication/Traits/HasAccessTokens.php
> +    public function generateAccessToken(string $name, array $scopes = ['*'], ?string $expiresAt = null): AccessToken
You are right, a ```string``` doesn't make sense in this situation, a ```Time``` type is the correct answer, specially, as you mentioned gives people more flexibility. What I do think happen was, I got caught up with the date/time format and then, mistakenly went with strings without re-evaluating.

2025-02-13 14:26 UTC, CosDiabos commented on src/Authentication/Traits/HasAccessTokens.php
> +    public function getAccessTokenTimeToExpire(?AccessToken $accessToken, string $format = 'date'): string|null
Like I've mentioned in my previous comment, I agree with you and will change it accordingly. The idea with this method initially, was to return the "humanized" representation easily but then for the sake of completeness, I also brought in the date which now makes more sense getting both from the Time object directly.

2025-02-13 14:26 UTC, CosDiabos commented on src/Authentication/Traits/HasAccessTokens.php
> +    public function hasAccessTokenExpired(?AccessToken $accessToken): bool|null
Yes, that makes more sense.

2025-02-14 09:36 UTC, datamweb commented
Is it possible to generate a token without a time limit?

2025-02-14 10:12 UTC, CosDiabos commented
> Is it possible to generate a token without a time limit?

Sure! Just skip that argument when generating a token. It will follow the defined token lifetime though.

2025-02-15 08:40 UTC, michalsn requested changes
@CosDiabos Thank you for the updates. I have a few other comments.

Of other things, I see that one action "Detect Merge Commits" reports an error. I'm not sure because of which commit, but you can try to rebase (there were some changes in the codebase since you started this PR). Or alternatively, if you identify the commit that is interfering, you can try to remove it from this PR - here are quite clear instructions that should help: https://graphite.dev/guides/how-to-delete-a-git-commit#deleting-old-or-specific-commits

@datamweb - is this failed action a deal breaker for us or not really?

2025-02-15 08:40 UTC, michalsn commented on docs/references/authentication/hmac.md
> +`hasHmacTokenExpired(AccessToken $HmacToken)` - Checks if the HMAC key has expired. Returns `true` if the HMAC key has expired, `false` if not, and `null` if the expire date is null.
```suggestion
`hasHmacTokenExpired(AccessToken $HmacToken)` - Checks if the HMAC key has expired. Returns `true` if the HMAC key has expired, `false` if not.
```

2025-02-15 08:40 UTC, michalsn commented on docs/references/authentication/hmac.md
> +$token = $this->user->generateHmacToken('foo', ['foo:bar'], $expiresAt);
```suggestion
$token = $this->user->generateHmacToken('foo', ['foo.bar'], $expiresAt);
```
Scope names should avoid using a colon, according to the docs.

2025-02-15 08:40 UTC, michalsn commented on docs/references/authentication/hmac.md
> +$expiresAt = $expiresAt->addDays(15);
```suggestion
$expiresAt = Time::now()->addMonths(1)->addDays(15);
```

2025-02-15 08:40 UTC, michalsn commented on docs/references/authentication/hmac.md
> +$token = $this->user->generateHmacToken('foo', ['foo:bar'], $expiresAt);
```suggestion
$token = $this->user->generateHmacToken('foo', ['foo.bar'], $expiresAt);
```

2025-02-15 08:40 UTC, michalsn commented on docs/references/authentication/hmac.md
> +$token = $this->user->generateHmacToken('foo', ['foo:bar'], $expiresAt);
```suggestion
$token = $this->user->generateHmacToken('foo', ['foo.bar'], $expiresAt);
```

2025-02-15 08:40 UTC, michalsn commented on docs/references/authentication/hmac.md
> +Expiration and Lifetime are different concepts. The lifetime is the maximum time allowed for the HMAC Key to exist since its last use. HMAC Key expiration, on the other hand, is a set date in which t
```suggestion
### HMAC Keys Expiration vs Lifetime

Expiration and Lifetime are different concepts. The lifetime is the maximum time allowed for the HMAC Key to exist since its last use. HMAC Key expiration, on the other hand, is a set date in which the HMAC Key will cease to function.
```
Just formatting - one line space between the heading and the content.

2025-02-15 08:40 UTC, michalsn commented on docs/references/authentication/tokens.md
> +$token = $this->user->generateAccessToken('foo', ['foo:bar'], $expiresAt);
```suggestion
$token = $this->user->generateAccessToken('foo', ['foo.bar'], $expiresAt);
```

2025-02-15 08:40 UTC, michalsn commented on docs/references/authentication/tokens.md
> +$expiresAt = $expiresAt->addDays(15);
```suggestion
$expiresAt = Time::now()->addMonths(1)->addDays(15);
```

2025-02-15 08:40 UTC, michalsn commented on docs/references/authentication/tokens.md
> +`hasAccessTokenExpired(AccessToken $accessToken)` - Checks if Access Token has expired. Returns `true` if the Access Token has expired, `false` if not, and `null` if the expire date is not set.
```suggestion
`hasAccessTokenExpired(AccessToken $accessToken)` - Checks if Access Token has expired. Returns `true` if the Access Token has expired, `false` if not.
```

2025-02-15 08:40 UTC, michalsn commented on docs/references/authentication/tokens.md
> +$token = $this->user->generateAccessToken('foo', ['foo:bar'], $expiresAt);
```suggestion
$token = $this->user->generateAccessToken('foo', ['foo.bar'], $expiresAt);
```

2025-02-15 08:40 UTC, michalsn commented on docs/references/authentication/tokens.md
> +$token = $this->user->generateAccessToken('foo', ['foo:bar'], $expiresAt);
```suggestion
$token = $this->user->generateAccessToken('foo', ['foo.bar'], $expiresAt);
```

2025-02-15 08:40 UTC, michalsn commented on src/Authentication/Traits/HasAccessTokens.php
> +    public function hasAccessTokenExpired(?AccessToken $accessToken): bool
```suggestion
    public function hasAccessTokenExpired(AccessToken $accessToken): bool
```
I don't think we should allow null.

2025-02-15 08:40 UTC, michalsn commented on src/Authentication/Traits/HasAccessTokens.php
> +        return isset($accessToken->expires);
```suggestion
        return $accessToken->expires !== null;
```
Since the existence of the object is guaranteed, we can go with a strict check.

2025-02-15 08:40 UTC, michalsn commented on src/Authentication/Traits/HasHmacTokens.php
> +    public function hasHmacTokenExpired(?AccessToken $accessToken): bool
```suggestion
    public function hasHmacTokenExpired(AccessToken $accessToken): bool
```

2025-02-15 08:40 UTC, michalsn commented on src/Authentication/Traits/HasAccessTokens.php
> +    public function setAccessTokenExpirationById(int $id, Time $expiresAt): bool
I wonder... since we already allow the expiration date to be changed, should we also allow the expiration to be removed altogether?

2025-02-15 08:40 UTC, michalsn commented on src/Authentication/Traits/HasHmacTokens.php
> +    public function setHmacTokenExpirationById(int $id, Time $expiresAt): bool
Same question as with `setAccessTokenExpirationById()` - should we allow `?Time`?

2025-02-15 08:40 UTC, michalsn commented on src/Authentication/Traits/HasHmacTokens.php
> +        return isset($accessToken->expires);
```suggestion
        return $accessToken->expires !== null;
```

2025-02-15 09:50 UTC, datamweb commented
> is this failed action a deal breaker for us or not really?

@michalsn , commit [e6c10c0d65c3360639fe39120d48e3949b740238](https://github.com/codeigniter4/shield/pull/1219/commits/e6c10c0d65c3360639fe39120d48e3949b740238) was correctly detected by the action. The user has likely used `pull` to update their branch, whereas we emphasize using `rebase` instead.  

We prefer **avoiding merge commits** to keep the *graph clean*, but it is *not mandatory*. However, based on your explanation, I believe the user should be able to handle the issue.  

If the user needs to update their branch, they should use `rebase` instead.
https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#updating-your-branch

2025-02-17 14:29 UTC, CosDiabos commented on src/Authentication/Traits/HasAccessTokens.php
> +    public function setAccessTokenExpirationById(int $id, Time $expiresAt): bool
I think it could be useful. Right now, if a expiration date is set, it can't be undone intuitively.

Would it be better to make its own method or clear it when it isn't present (`?Time` as you mentioned)?

2025-02-17 14:33 UTC, CosDiabos commented on src/Authentication/Traits/HasAccessTokens.php
> +    public function hasAccessTokenExpired(?AccessToken $accessToken): bool
Yeah, that make sense.

I also noticed that  `setAccessToken()` and `setHmacToken()` are allowing a null value, and they probably shouldn't unless there is a reason to clear the access/hmac token.

2025-02-17 14:44 UTC, CosDiabos commented
Hey!

Thank you all for your help and support.

Yes I had merged because I had a couple of out of date files that I was working on. I've removed the merge commit with the rebase. I think now everything is in order with most change requests updated!

2025-02-18 07:59 UTC, michalsn reviewed
As for Psalm errors, this is out of the scope of this PR. Seems like the new release has changed some default settings. You can add `ensureOverrideAttribute="false"` to the `psalm.xml` file, right after `findUnusedCode="false"` to fix this.

2025-02-18 07:59 UTC, michalsn commented on src/Authentication/Traits/HasAccessTokens.php
> +    public function setAccessTokenExpirationById(int $id, Time $expiresAt): bool
`?Time` is enough - I don't think we need a separate method for this. But this will require changes also to the `setIdentityExpirationById()` method.

2025-02-18 07:59 UTC, michalsn commented on docs/references/authentication/tokens.md
> +Expiration and Lifetime are different concepts. The lifetime is the maximum time allowed for the token to exist since its last use. Token expiration, on the other hand, is a set date in which the Acc
Please add a line break between the section header and the content.

2025-02-18 08:01 UTC, michalsn commented on src/Authentication/Traits/HasAccessTokens.php
> +    public function hasAccessTokenExpired(?AccessToken $accessToken): bool
Well, the `$accessToken` in `setAccessToken()` and `setHmacToken()` can be `null`, because the user may simply have no token (e.g. see `AccessTokens::loginById()`). 

But this new method doesn't rely on the `$this->currentAccessToken` property, but is rather intended to be used to administer tokens when we use `accessTokens()`. So, my thinking was the `$accessToken` should not be optional.

2025-02-18 08:57 UTC, CosDiabos commented on src/Authentication/Traits/HasAccessTokens.php
> +    public function setAccessTokenExpirationById(int $id, Time $expiresAt): bool
Great, sounds good!

2025-02-18 09:30 UTC, CosDiabos commented
> As for Psalm errors, this is out of the scope of this PR. Seems like the new release has changed some default settings. You can add `ensureOverrideAttribute="false"` to the `psalm.xml` file, right after `findUnusedCode="false"` to fix this.

Yeah, I skimmed the errors looking for a file that I could have edited but couldn't find it. Thanks for the tip.

2025-02-18 19:51 UTC, michalsn approved these changes
Thank you - it looks good. Let's see what others think.

2025-02-19 02:08 UTC, datamweb requested changes
@CosDiabos Thank you for submitting the PR, and I apologize for the long delay. I have provided some suggested changes.  

Regarding the method names, my understanding is based on the documentation, but I might have misinterpreted it. If I have misunderstood any part of the code, I would appreciate your clarification.

2025-02-19 02:08 UTC, datamweb commented on docs/references/authentication/hmac.md
> +HMAC keys can be set to expire through the `generateHmacToken()` method. This takes the expiration date as the $expiresAt argument. To update or remove an existing HMAC key expiration date use `setHm
```suggestion
HMAC keys can be set to expire through the `generateHmacToken()` method. This takes the expiration date as the `$expiresAt` argument. To update or remove an existing HMAC key expiration date use `setHmacTokenExpirationById($HmacTokenID, $expiresAt)`
```

2025-02-19 02:08 UTC, datamweb commented on docs/references/authentication/hmac.md
> +`$expiresAt` [Time](/libraries/time.html) object
```suggestion
`$expiresAt` [Time](https://codeigniter.com/user_guide/libraries/time.html) object
```

2025-02-19 02:08 UTC, datamweb commented on docs/references/authentication/hmac.md
> +$token = $this->user->generateHmacToken('foo', ['foo:bar'], $expiresAt);
```suggestion
$token = $this->user->generateHmacToken('foo', ['foo.bar'], $expiresAt);
```

2025-02-19 02:08 UTC, datamweb commented on docs/references/authentication/hmac.md
> +HMAC keys can be set to expire through the `generateHmacToken()` method. This takes the expiration date as the $expiresAt argument. To update or remove an existing HMAC key expiration date use `setHm
_To update or remove an existing HMAC key expiration date use `setHmacTokenExpirationById($HmacTokenID, $expiresAt)`_

Since these are two distinct responsibilities, I think it's better to create separate functions for updating and removing the HMAC token expiration. This improves code clarity and maintainability.  

Update expiration date:
   ```php
   public function updateHmacTokenExpiration($hmacTokenID,  $expiresAt): bool
   ```
Remove expiration date (set to null)
   ```php
   public function removeHmacTokenExpiration($hmacTokenID): bool
   ```

What do you think?

2025-02-19 02:08 UTC, datamweb commented on docs/references/authentication/hmac.md
> +`hasHmacTokenExpired(AccessToken $HmacToken)` - Checks if the HMAC key has expired. Returns `true` if the HMAC key has expired, `false` if not.
Wouldn't it be better to use `isHmacTokenExpired` instead of `hasHmacTokenExpired`? 
This name is clearer and more naturally indicates that the function checks whether the token has expired.

2025-02-19 02:08 UTC, datamweb commented on docs/references/authentication/hmac.md
> +`canHmacTokenExpire(AccessToken $HmacToken)` - Checks if HMAC key has an expiration set. Returns `true` or `false` accordingly.
Wouldn't `hasHmacTokenExpiry` be a better choice instead of `canHmacTokenExpire`? 
The word **hasExpiry** more clearly indicates whether the token has an expiration set, avoiding potential confusion with can, which might imply permission or the ability to change.

2025-02-19 02:08 UTC, datamweb commented on docs/references/authentication/hmac.md
> +```
```suggestion
```console
```

2025-02-19 02:08 UTC, datamweb commented on docs/references/authentication/hmac.md
> +**Careful!** This command invalidates _all_ keys for _all_ users.
```suggestion
**Careful!** This command invalidates _all_ keys for _all_ users.

!!! warning

    This command invalidates _all_ keys for _all_ users.
```

2025-02-19 02:08 UTC, datamweb commented on docs/references/authentication/tokens.md
> +Access Tokens can be set to expire through the `generateAccessToken()` method. This takes the expiration date as the $expiresAt argument. To update or remove an existing HMAC key expiration date use
```suggestion
Access Tokens can be set to expire through the `generateAccessToken()` method. This takes the expiration date as the `$expiresAt` argument. To update or remove an existing HMAC key expiration date use `setAccessTokenById($HmacTokenID, $expiresAt)`
```
I have the same question about the function name `setHmacTokenExpirationById` here as well. What do you think? 😃

2025-02-19 02:08 UTC, datamweb commented on docs/references/authentication/tokens.md
> +`$expiresAt` [Time](/libraries/time.html) object
```suggestion
`$expiresAt` [Time](https://codeigniter.com/user_guide/libraries/time.html) object
```

2025-02-19 02:08 UTC, datamweb commented on docs/references/authentication/tokens.md
> +`canAccessTokenExpire(AccessToken $HmacToken)` - Checks if Access Token has an expiration set. Returns `true` or `false` accordingly.
What do you think? 😃
```suggestion
`hasAccessTokenExpiry(AccessToken $HmacToken)` - Checks if Access Token has an expiration set. Returns `true` or `false` accordingly.
```

2025-02-19 02:08 UTC, datamweb commented on docs/references/authentication/tokens.md
> +`hasAccessTokenExpired(AccessToken $accessToken)` - Checks if Access Token has expired. Returns `true` if the Access Token has expired, `false` if not.
What do you think? 😃
```suggestion
`isAccessTokenExpired(AccessToken $accessToken)` - Checks if Access Token has expired. Returns `true` if the Access Token has expired, `false` if not.
```

2025-02-19 02:08 UTC, datamweb commented on src/Authentication/Authenticators/AccessTokens.php
> +                Time::now(),
Did the tools add this, or is it extra?
```suggestion
                Time::now()
```

2025-02-19 02:08 UTC, datamweb commented on src/Models/UserIdentityModel.php
> +            ->where('type', $type_token)
If the `$type_token` is `null`, what happens with the `where('type', $type_token) `condition?

2025-02-19 02:08 UTC, datamweb commented on tests/Authentication/HasAccessTokensTest.php
> +        $tokenExpiration = $tokenExpiration->addYears(1);
```suggestion
        $tokenExpiration = $tokenExpiration->addYears(1)->addMonths(1);
```

2025-02-19 02:08 UTC, datamweb commented on tests/Authentication/HasHmacTokensTest.php
> +        $tokenExpiration = $tokenExpiration->addYears(1);
```suggestion
        $tokenExpiration = $tokenExpiration->addYears(1)->addMonths(1);
```

2025-02-19 02:08 UTC, datamweb commented on tests/Authentication/HasHmacTokensTest.php
> +        $tokenExpiration = $tokenExpiration->addYears(1);
```suggestion
        $tokenExpiration = Time::now()->addYears(1);
```

2025-02-19 02:08 UTC, datamweb commented on tests/Authentication/HasHmacTokensTest.php
> +        $tokenExpiration = $tokenExpiration->addYears(1);
```suggestion
        $tokenExpiration = Time::now()->addYears(1);
```

2025-02-19 05:40 UTC, kenjis commented on src/Authentication/Traits/HasHmacTokens.php
> +     * @param Time         $expiresAt Expiration date
```suggestion
     * @param Time|null    $expiresAt Expiration date
```

2025-02-19 05:42 UTC, kenjis commented on src/Authentication/Traits/HasAccessTokens.php
> +     * @param Time         $expiresAt Expiration date
```suggestion
     * @param Time|null    $expiresAt Expiration date
```

2025-02-19 05:47 UTC, kenjis commented on docs/references/authentication/hmac.md
> +HMAC keys can be set to expire through the `generateHmacToken()` method. This takes the expiration date as the $expiresAt argument. To update or remove an existing HMAC key expiration date use `setHm
Yes, I also think `update***()` and `remove***()` would be better.

2025-02-19 09:54 UTC, CosDiabos commented on docs/references/authentication/hmac.md
> +HMAC keys can be set to expire through the `generateHmacToken()` method. This takes the expiration date as the $expiresAt argument. To update or remove an existing HMAC key expiration date use `setHm
Yeah, michalsn and I talked about that same question (separation) earlier and kept everything on the same method.

However, I understand that the difference in functionality should warrant their own methods, also makes the removal of the expiration more conscious and less error prone action. I agree in splitting the actions.

2025-02-19 09:57 UTC, CosDiabos commented on docs/references/authentication/hmac.md
> +`hasHmacTokenExpired(AccessToken $HmacToken)` - Checks if the HMAC key has expired. Returns `true` if the HMAC key has expired, `false` if not.
I agree it's better semantically.

2025-02-19 10:00 UTC, CosDiabos commented on src/Authentication/Authenticators/AccessTokens.php
> +                Time::now(),
Yes it's from the CS tool. Due to 'trailing_comma_in_multiline' rule, I guess.

2025-02-19 10:11 UTC, CosDiabos commented on src/Models/UserIdentityModel.php
> +            ->where('type', $type_token)
Actually, it shouldn't be accepting a null value for that argument because `$type_token` should always be defined (Access or Hmac).

But, what I'm realising is if the `$id` is already provided, the `$type_token` arg and ` ->where('type', $type_token)` on the update seems too much since the `$id` already points there.

2025-02-19 14:11 UTC, datamweb commented on docs/references/authentication/hmac.md
> +    This command invalidates _all_ keys for _all_ users.
```suggestion

    This command invalidates _all_ keys for _all_ users.
```

2025-02-19 15:01 UTC, datamweb commented on docs/references/authentication/hmac.md
> +$this->user->hasHmacTokenExpired($token); // Returns true
Did you mean?
```suggestion
$this->user->isHmacTokenExpired($token); // Returns true
```

2025-02-19 15:01 UTC, datamweb commented on docs/references/authentication/hmac.md
> +$this->user->canHmacTokenExpire($token); // Returns true
And ?

2025-02-19 15:01 UTC, datamweb commented on docs/references/authentication/hmac.md
> +$this->user->canHmacTokenExpire($token2); // Returns false
And?

2025-02-19 15:01 UTC, datamweb commented on docs/references/authentication/tokens.md
> +$this->user->hasAccessTokenExpired($token); // Returns true
And?
```suggestion
$this->user->isAccessTokenExpired($token); // Returns true
```

2025-02-19 15:01 UTC, datamweb commented on docs/references/authentication/tokens.md
> +$this->user->canAccessTokenExpire($token2); // Returns false
And?
```suggestion
$this->user->canAccessTokenExpire($token2); // Returns false
```

2025-02-19 15:01 UTC, datamweb commented on docs/references/authentication/tokens.md
> +$this->user->canAccessTokenExpire($token); // Returns true
And?
```suggestion
$this->user->canAccessTokenExpire($token); // Returns true
```

2025-02-19 15:25 UTC, datamweb approved these changes
Please update the PR description. Also, be aware that, based on coordination with the team, others may provide suggestions for improvements here. I appreciate your patience in advance.

2025-02-19 15:34 UTC, paulbalandan commented on docs/references/authentication/tokens.md
> +Tokens will expire after a specified amount of time has passed since they last have been used.
```suggestion
Tokens will expire after a specified amount of time has passed since they have last been used.
```

2025-02-19 15:34 UTC, paulbalandan commented on src/Authentication/Traits/HasHmacTokens.php
> +     * @return bool Returns true if Access Token is expired, false if not
This comment is unnecessary as it can be inferred from the method description what it does.
```suggestion
```

2025-02-19 15:34 UTC, paulbalandan commented on src/Authentication/Traits/HasAccessTokens.php
> +     * @return bool Returns true if Access Token is expired, false if not
```suggestion
```

2025-02-19 15:34 UTC, paulbalandan commented on src/Authentication/Traits/HasAccessTokens.php
> +     * Checks if the current Hmac token can expire
```suggestion
     * Checks if the access token has a set expiration date
```

2025-02-19 15:34 UTC, paulbalandan commented on src/Authentication/Traits/HasAccessTokens.php
> +     * @return bool Returns true if AccessToken can expire.
```suggestion
```

2025-02-19 15:34 UTC, paulbalandan commented on src/Authentication/Traits/HasHmacTokens.php
> +     * Checks if the current Hmac token can expire
```suggestion
     * Checks if the current HMAC token has a set expiration date
```

2025-02-19 15:34 UTC, paulbalandan commented on src/Authentication/Traits/HasHmacTokens.php
> +     * @return bool Returns true if Hmac Token can expire.
```suggestion
```

2025-02-19 15:34 UTC, paulbalandan commented on src/Commands/Hmac.php
> +        $that = $this;
Why do you need to assign `$this` to a variable? You can just make the closure below as not static then just access `$this->write` normally.

2025-02-19 15:34 UTC, paulbalandan commented on src/Commands/Hmac.php
> +            static function ($identity) use ($uIdModelSub, $that): void {
```suggestion
            function ($identity) use ($uIdModelSub): void {
```

2025-02-19 15:34 UTC, paulbalandan commented on src/Commands/Hmac.php
> +                $timeNow = Time::now(); // Current date/time
```suggestion
                $timeNow = Time::now();
```

2025-02-19 15:34 UTC, paulbalandan commented on src/Commands/Hmac.php
> +                    $that->write('Hmac Key/Token ID: ' . $identity->id . ', already expired, skipped.');
```suggestion
                    $this->write('Hmac Key/Token ID: ' . $identity->id . ', already expired, skipped.');
```

2025-02-19 15:34 UTC, paulbalandan commented on src/Commands/Hmac.php
> +                $that->write('Hmac Key/Token ID: ' . $identity->id . ', set as expired.');
```suggestion
                $this->write('Hmac Key/Token ID: ' . $identity->id . ', set as expired.');
```

2025-02-19 17:31 UTC, CosDiabos commented
> Please update the PR description. Also, be aware that, based on coordination with the team, others may provide suggestions for improvements here. I appreciate your patience in advance.

Updated! No problem!

2025-02-20 15:34 UTC, CosDiabos commented on src/Commands/Hmac.php
> +        $that = $this;
Hey!

Thanks! I wasn't sure about how the Closure worked, and the docs sample for `chunk()` uses a static method, which, seemed the right way to do it.

2025-02-21 13:01 UTC, paulbalandan reviewed
Some grammar fixes

2025-02-21 13:01 UTC, paulbalandan commented on docs/references/authentication/hmac.md
> +By default, the HMAC keys don't expire unless they meet the HMAC Keys lifetime expiration after their last used date.
```suggestion
By default, the HMAC keys don't expire unless they reach the HMAC keys' lifetime expiration after their last use date.
```

2025-02-21 13:01 UTC, paulbalandan commented on docs/references/authentication/hmac.md
> +HMAC keys can be set to expire through the `generateHmacToken()` method. This takes the expiration date as the `$expiresAt` argument. To update an existing HMAC key expiration date use `updateHmacTok
```suggestion
HMAC keys can be set to expire through the `generateHmacToken()` method. This takes the expiration date as the `$expiresAt` argument. To update an existing HMAC key expiration date, use `updateHmacTokenExpiration($hmacTokenID, $expiresAt)`. To remove it, use `removeHmacTokenExpiration($hmacTokenID)`.
```

2025-02-21 13:01 UTC, paulbalandan commented on docs/references/authentication/hmac.md
> +`isHmacTokenExpired(AccessToken $HmacToken)` - Checks if the HMAC key is expired. Returns `true` if the HMAC key is expired, `false` if not.
```suggestion
`isHmacTokenExpired(AccessToken $hmacToken)` - Checks if the HMAC key is expired. Returns `true` if the HMAC key is expired; otherwise, returns `false`.
```

2025-02-21 13:01 UTC, paulbalandan commented on docs/references/authentication/hmac.md
> +`hasHmacTokenExpiry(AccessToken $HmacToken)` - Checks if HMAC key has an expiration set. Returns `true` or `false` accordingly.
```suggestion
`hasHmacTokenExpiry(AccessToken $hmacToken)` - Checks if HMAC key has an expiration set. Returns `true` if the HMAC key is expired; otherwise, returns `false`.
```

2025-02-21 13:01 UTC, paulbalandan commented on docs/references/authentication/hmac.md
> +Expiration and Lifetime are different concepts. The lifetime is the maximum time allowed for the HMAC Key to exist since its last use. HMAC Key expiration, on the other hand, is a set date in which t
```suggestion
Expiration and lifetime are two different concepts. The lifetime is the maximum time allowed for the HMAC Key to exist since its last use. HMAC Key expiration, on the other hand, is a set date in which the HMAC Key will cease to function.
```

2025-02-21 13:01 UTC, paulbalandan commented on docs/references/authentication/tokens.md
> +By default, the Access Tokens don't expire unless they meet the Access Token lifetime expiration after their last used date.
```suggestion
By default, the Access Tokens don't expire unless they reach the Access Token's lifetime expiration after their last use date.
```

2025-02-21 13:01 UTC, paulbalandan commented on docs/references/authentication/tokens.md
> +Access Tokens can be set to expire through the `generateAccessToken()` method. This takes the expiration date as the `$expiresAt` argument. To update an existing HMAC key expiration date use `updateA
```suggestion
Access Tokens can be set to expire through the `generateAccessToken()` method. This takes the expiration date as the `$expiresAt` argument. To update an existing HMAC key expiration date, use `updateAcessTokenExpiration($accessTokenID, $expiresAt)`. To remove it, use `removeAccessTokenExpiration($accessTokenID)`.
```

2025-02-21 13:01 UTC, paulbalandan commented on docs/references/authentication/tokens.md
> +`isAccessTokenExpired(AccessToken $accessToken)` - Checks if Access Token is expired. Returns `true` if the Access Token is expired, `false` if not.
```suggestion
`isAccessTokenExpired(AccessToken $accessToken)` - Checks if Access Token is expired. Returns `true` if the Access Token is expired; otherwise, returns `false`.
```

2025-02-21 13:01 UTC, paulbalandan commented on docs/references/authentication/tokens.md
> +`hasAccessTokenExpiry(AccessToken $HmacToken)` - Checks if Access Token has an expiration set. Returns `true` or `false` accordingly.
```suggestion
`hasAccessTokenExpiry(AccessToken $accessToken)` - Returns `true` if the Access Token has a set expiration date; otherwise, returns `false`.
```

2025-02-21 13:01 UTC, paulbalandan commented on docs/references/authentication/tokens.md
> +Expiration and Lifetime are different concepts. The lifetime is the maximum time allowed for the token to exist since its last use. Token expiration, on the other hand, is a set date in which the Acc
```suggestion
Expiration and lifetime are two different concepts. The lifetime is the maximum time allowed for the token to exist since its last use. Token expiration, on the other hand, is a set date in which the Access Token will cease to function.
```

2025-02-21 13:01 UTC, paulbalandan commented on src/Authentication/Traits/HasHmacTokens.php
> +    }
```suggestion
     * Checks if the provided HMAC Token is expired.
     */
    public function isHmacTokenExpired(AccessToken $hmacToken): bool
    {
        return $hmacToken->expires !== null && $hmacToken->expires->isBefore(Time::now());
    }
```

2025-02-21 13:01 UTC, paulbalandan commented on src/Authentication/Traits/HasHmacTokens.php
> +     * @param int  $id        AccessToken ID
```suggestion
     * @param int  $id        HMAC Token ID
```

2025-02-21 13:01 UTC, paulbalandan commented on src/Authentication/Traits/HasHmacTokens.php
> +     * @param int $id AccessToken ID
```suggestion
     * @param int $id HMAC Token ID
```

2025-02-21 13:01 UTC, paulbalandan commented on src/Authentication/Traits/HasHmacTokens.php
> +    }
```suggestion
    public function hasHmacTokenExpiry(AccessToken $hmacToken): bool
    {
        return $hmacToken->expires !== null;
    }
```

2025-02-22 12:06 UTC, paulbalandan approved these changes

2025-02-24 08:59 UTC, michalsn commented on src/Authentication/Traits/HasAccessTokens.php
> +    public function hasAccessTokenExpiry(AccessToken $accessToken): bool
I'm not sure if this has been changed or if it was here from the beginning, but reading the code, I thought: "Wait a minute, don't we have two methods with the same functionality?".

If someone reads the method name without checking its implementation, they might assume it returns true when the token is already expired, not just when an expiry date is set.

IMO "Has expiry" could be interpreted as "Has the token expired?" instead of "Does it have an expiry date?".

Maybe we could go with `canAccessTokenExpire()` or `isAccessTokenExpirable()`?

Same thing for Hmac.

2025-02-24 10:52 UTC, CosDiabos commented on src/Authentication/Traits/HasAccessTokens.php
> +    public function hasAccessTokenExpiry(AccessToken $accessToken): bool
The method names have been a challenge so far, haha.

> 
> Maybe we could go with `canAccessTokenExpire()` or `isAccessTokenExpirable()`?
> 

I don't think `hasAccessTokenExpiry()` is necessarily confusing, but `canAccessTokenExpire()` seems to be more straightforward. `isAccessTokenExpirable()` is confusing, imo

2025-02-24 10:58 UTC, michalsn commented on src/Authentication/Traits/HasAccessTokens.php
> +    public function hasAccessTokenExpiry(AccessToken $accessToken): bool
> The method names have been a challenge so far, haha.

Yeah, apparently 😆 

Let's wait a day - if there are no more opinions on the subject, choose what you think is best.

2025-02-26 06:14 UTC, michalsn approved these changes

2025-02-26 19:46 UTC, samsonasik commented on src/Authentication/Authenticators/AccessTokens.php
> +            $token->expires !== null
can this use instanceof, eg : 

```suggestion
            $token->expires instanceof Time
```

2025-02-27 12:45 UTC, michalsn commented on src/Authentication/Authenticators/AccessTokens.php
> +            $token->expires !== null
Sounds good.

2025-02-28 07:43 UTC, michalsn commented on src/Authentication/Authenticators/AccessTokens.php
> +            $token->expires !== null
@CosDiabos Would you find time for these final changes? I'm looking forward to merging this PR. Thanks!

2025-02-28 10:53 UTC, michalsn commented on src/Authentication/Traits/HasAccessTokens.php
> +    public function CanAccessTokenExpire(AccessToken $accessToken): bool
```suggestion
    public function canAccessTokenExpire(AccessToken $accessToken): bool
```
On more issue. The same applies to HMAC + all the mentions in the docs.

2025-03-03 08:10 UTC, merged

2025-03-03 08:10 UTC, michalsn commented
@CosDiabos Thank you for your updates and patience, and congratulations on your first contribution to the project!

2025-03-06 09:22 UTC, CosDiabos commented
@michalsn You're welcome! Thank you all for your help and reviews throughout.