Standardize variadic passing of groups/permissions
codeigniter4/shield pull request #256
Opened 2022-06-25 04:51 UTC by lonnieezell

- Standardize variadic passing of groups/permissions to the syncGroups and syncPermissions methods. 
- Added docs for groups to the quick start.

2022-06-25 11:01 UTC, MGatner approved these changes
I like the change to variadic with types. I can't tell what changed in the quick start until this is rebased after the initial quick start PR.

2022-06-28 23:11 UTC, kenjis requested changes
#255 should be merged first, and
`docs/2 - quickstart.md` should be renamed.

2022-07-01 04:58 UTC, lonnieezell commented on docs/2 - quickstart.md
> +
This is handled by the `can()` method below.

2022-07-01 04:59 UTC, lonnieezell commented
Closing - new PR #266 is same thing, but cleaned up.

2022-07-01 04:59 UTC, closed without merging