Use variadic passing of groups/permissions
codeigniter4/shield pull request #266
Opened 2022-07-01 04:54 UTC by lonnieezell

- Standardize variadic passing of groups/permissions to the syncGroups and syncPermissions methods.
- Added docs for groups to the quick start.

2022-07-01 05:07 UTC, kenjis commented on src/Authorization/Traits/Authorizable.php
> +    public function syncGroups(...$groups): self
```suggestion
    public function syncGroups(string ...$groups): self
```

2022-07-01 05:07 UTC, kenjis commented on src/Authorization/Traits/Authorizable.php
> +    public function syncPermissions(...$permissions): self
```suggestion
    public function syncPermissions(string ...$permissions): self
```

2022-07-01 10:39 UTC, MGatner requested changes

2022-07-01 10:39 UTC, MGatner commented on docs/quickstart.md
> +if($user->inGroup('admin', 'beta')) {
```suggestion
if ($user->inGroup('admin', 'beta')) {
```

2022-07-01 10:39 UTC, MGatner commented on docs/quickstart.md
> +if($user->inGroup('admin')) {
```suggestion
if ($user->inGroup('admin')) {
```

2022-07-02 04:19 UTC, kenjis approved these changes

2022-07-02 10:18 UTC, MGatner approved these changes
💪😊👍

2022-07-02 10:18 UTC, merged