chore: add language unit tests
codeigniter4/shield pull request #274
Opened 2022-07-02 22:08 UTC by kenjis

2022-07-03 02:01 UTC, datamweb commented
I thought this had been covered before! I really like this PR.

2022-07-03 02:57 UTC, lonnieezell approved these changes

2022-07-03 11:46 UTC, MGatner requested changes
This is great!

2022-07-03 11:46 UTC, MGatner commented on .github/workflows/phpunit-lang.yml
> +          php-version: '8.0'
I've started using `8.1` for our "generical" workflows:
```suggestion
          php-version: '8.1'
```

2022-07-04 10:42 UTC, MGatner approved these changes

2022-07-04 10:43 UTC, merged