Spanish (Spain) translation
codeigniter4/shield pull request #357
Opened 2022-08-10 08:00 UTC by treborin

2022-08-10 08:20 UTC, datamweb commented
Hey @treborin ,
Thank you for contributing!
Please see https://github.com/codeigniter4/shield/pull/235#issuecomment-1153050805

2022-08-10 08:47 UTC, treborin commented
> Hey @treborin , Thank you for contributing! Please see [#235 (comment)](https://github.com/codeigniter4/shield/pull/235#issuecomment-1153050805)

@datamweb . Done!

2022-08-10 08:55 UTC, datamweb requested changes

2022-08-10 08:55 UTC, datamweb commented on tests/Language/AbstractTranslationTestCase.php
> +        SpanishTranslationTest::class                      => 'es',
Please fix the coding style. **just run :**
`composer cs-fix`

2022-08-10 09:53 UTC, datamweb commented
It looks like you are using GitHub UI to post this PR.
Please rename file `tests/Language/SpanishTranslationTest` to `tests/Language/SpanishTranslationTest.php`.
Then tell me if there is any problem in executing command `composer cs-fix`?

2022-08-10 11:06 UTC, datamweb commented
> ![image](https://user-images.githubusercontent.com/31905622/183878098-de0216bd-6fd7-40b0-ab61-c1d202e045d9.png)

@kenjis , Does executing command `composer update` solve this problem?

2022-08-10 11:42 UTC, kenjis commented
@treborin run `composer update` and `composer cs-fix` in the repository root directory, that is `shield`.

2022-08-10 13:07 UTC, treborin commented
> @treborin run `composer update` and `composer cs-fix` in the repository root directory, that is `shield`.

@kenjis , cmposer update, ok. But here is composer cs-fix:
![image](https://user-images.githubusercontent.com/31905622/183908489-47498edd-0e1b-4043-a9cd-c42d3c8155e8.png)

@datamweb, i fixed coding style by hand. I saw inside unsuccessfuls checks thay te problem was the file text format, that need to be ansii. And i fixed it by hand, line by line.

2022-08-10 13:15 UTC, datamweb commented
Yes, I got it.
try 
`mkdir build`
`composer update` 
`composer cs-fix`

2022-08-10 13:35 UTC, treborin commented
> Yes, I got it. try `mkdir build` `composer update` `composer cs-fix`

![image](https://user-images.githubusercontent.com/31905622/183914539-57d11fb7-e832-4891-8b30-774721b3f1a3.png)
![image](https://user-images.githubusercontent.com/31905622/183914862-116388da-7b0e-4215-957e-b24d0459b1d5.png)

2022-08-11 10:41 UTC, MGatner commented
The `cs-fix` command was just added this week (#340). If your fork was from earlier the command would be `composer style`. Either way that is simply an alias, you can run the command directly:
```shell
php vendor/bin/php-cs-fixer fix --ansi
```

2022-08-11 10:43 UTC, MGatner commented
I don't know what is happening with those action failures. The tests all pass but a PHP error occurs when it tries to gather coverage. I believe it is unrelated to this PR.

2022-08-11 14:34 UTC, treborin commented
> I don't know what is happening with those action failures. The tests all pass but a PHP error occurs when it tries to gather coverage. I believe it is unrelated to this PR.

I try with a new PR

2022-08-11 14:34 UTC, closed without merging