fix: redirect()->withInput() or withErrors() causes ValidationException
codeigniter4/shield pull request #383
Opened 2022-08-15 22:25 UTC by kenjis

https://github.com/codeigniter4/shield/discussions/381

2022-08-16 06:16 UTC, datamweb commented
@kenjis, I think we should merge this PR.
The number of people involved in PR seems to be high.
according to what you did recently for **hotfix CI**, we can proceed to write the test after the merge.

2022-08-16 07:15 UTC, jozefrebjak commented
+1 for merge now, It's breaking app at all.

2022-08-16 08:27 UTC, kenjis commented
To merge, we need reviews.

2022-08-16 09:58 UTC, jozefrebjak commented
@kenjis For me this PR solved validation in forms.

2022-08-16 10:48 UTC, MGatner commented
I don't like the production use of reflection. It's hard to trace this back in mobile, but couldn't this be solved by handling our validations from a clean instance?
```php
// Validate the registration
if (! single_service('validation')->setRules($this->registrationRules)->run($event)) {
...
```

2022-08-16 10:55 UTC, kenjis commented
> couldn't this be solved by handling our validations from a clean instance?

No, because the session data ($_SESSION) is global.

See https://github.com/codeigniter4/CodeIgniter4/pull/6381
It helps your understanding.

2022-08-16 11:05 UTC, MGatner commented
That helps! Okay I am on board with the Reflection solution. It's a hack but we have a fix in `framework` at least. Maybe add a note that if the minimum CI4 version is ever increased past 4.2.4 then it can be refactored. Or alternatively, check the actual version and have Reflection be the fallback solution.

2022-08-16 11:05 UTC, MGatner requested changes
_See comment above_

2022-08-16 11:25 UTC, datamweb approved these changes
After applying comment **MGatner** , I don't see any problem.

![Screenshot 2022-08-16 145031](https://user-images.githubusercontent.com/9530214/184867896-9c1e61ec-d997-457a-8a8a-0fbdc20bbcb9.jpg)

2022-08-21 10:28 UTC, MGatner approved these changes
👍

2022-08-21 11:33 UTC, merged