refactor: Auth Actions
codeigniter4/shield pull request #397
Opened 2022-08-20 04:47 UTC by kenjis

Need to rebase after merging #391

2022-08-20 11:20 UTC, MGatner commented
I'll need to come back to these two another day.

2022-08-21 10:34 UTC, MGatner commented
Awaiting rebase.

2022-08-22 10:28 UTC, MGatner approved these changes
Looks good to me. I'm still not actually using Shield in any projects so let's be sure to get another review from someone. @datamweb and/or @lonnieezell?

2022-08-22 19:51 UTC, datamweb approved these changes
@kenjis code works fine, and I didn't see any problems.
**Thanks**
During the review of this PR, I noticed an issue, which I thought was better to raise here.
1. Register a new user.By default, every user login the system after registration.
2 . Check the table with command `php spark db:table test__auth_logins`.
Why is the user's login not recorded in the table?!!
It seems that we need PR to cover this issue.

2022-08-22 21:43 UTC, kenjis commented
> Why is the user's login not recorded in the table?!!

It is intentional.
Because it is not a login to record. It is a registration.
A login to record is a user action to login.
I think that a user does not think they are logged in when they register.

The current specification is stated in #131

2022-08-23 17:45 UTC, datamweb commented
> It is intentional. 

Thanks Kenjis, I will check #131.

2022-08-23 23:15 UTC, kenjis commented
Updated the docs.

2022-08-24 02:09 UTC, kenjis commented
I refactored action classes to be more extensible. 

Now you can probably extend the action class to use time limited multiple codes:
https://github.com/codeigniter4/shield/discussions/343#discussioncomment-3416568

2022-08-24 10:55 UTC, MGatner approved these changes
Looks good! I'm glad to see some of the ambiguity cleared up. I can't keep track of what has been released... Do we need to start a changelog for some of these behavior changes?

2022-08-24 17:01 UTC, datamweb requested changes
I think the following change will help the readability of the documents(`auth_actions.md`)
1. **Email-based Account Activation** 
2. **Email-based Two Factor Authentication** 

I prefer to check this PR locally more carefully so I need more time.
If you are not in a hurry to merge, wait a little.

2022-08-24 17:27 UTC, datamweb requested changes

2022-08-24 17:27 UTC, datamweb commented on tests/Unit/EmailActivatorTest.php
> +        $this->expectExceptionMessage('Cannot get the pending login User');
```suggestion
        $this->expectExceptionMessage('Cannot get the pending login User.');
```

2022-08-24 17:27 UTC, datamweb commented on tests/Unit/EmailActivatorTest.php
> +        $this->expectExceptionMessage('Cannot get the pending login User');
```suggestion
        $this->expectExceptionMessage('Cannot get the pending login User.');
```

2022-08-25 02:24 UTC, kenjis commented on tests/Unit/EmailActivatorTest.php
> +        $this->expectExceptionMessage('Cannot get the pending login User');
Done.

2022-08-25 02:25 UTC, kenjis commented
@datamweb 
> I prefer to check this PR locally more carefully so I need more time.

Okay. I don't hurry.

2022-08-25 20:25 UTC, datamweb approved these changes
Well! 
After hours of playing with the code, I found no problem.

2022-08-26 01:29 UTC, merged

2022-08-26 01:31 UTC, kenjis commented
@datamweb Thank you for your testing!