docs: add some important shield features to `README.md`
codeigniter4/shield pull request #427
Opened 2022-09-10 04:32 UTC by datamweb

2022-09-11 10:08 UTC, MGatner requested changes
This is a great overview, but it feels too long for the top of the docs "landing page". I would recommend trying to cut it in half and make it bullet points instead of numbers; we can still find a place for the full list on another page.

2022-09-13 04:50 UTC, datamweb commented
> This is a great overview, but it feels too long for the top of the docs "landing page". I would recommend trying to cut it in half and make it bullet points instead of numbers; we can still find a place for the full list on another page.

I did it, but I think it's still not good! What do you think?

2022-09-13 09:35 UTC, MGatner approved these changes
Yes I think that's much better! It highlights some of our coolest features but still fits comfortably on the page. Thank you!

2022-09-14 00:43 UTC, kenjis approved these changes

2022-09-14 00:44 UTC, merged