fix: correct display of the error in case of change `authenticatorHeader`
codeigniter4/shield pull request #442
Opened 2022-09-17 18:00 UTC by datamweb

2022-09-18 08:26 UTC, kenjis approved these changes

2022-09-18 10:21 UTC, MGatner approved these changes

2022-09-19 05:37 UTC, datamweb commented
Add a note in the documentation and change the test commit message.

2022-09-19 10:38 UTC, MGatner requested changes
Looks good! Small proofreading

2022-09-19 10:38 UTC, MGatner commented on docs/guides/mobile_apps.md
> +> By default, `$authenticatorHeader['tokens']` is set to `Authorization`. You can change this value by setting the `$authenticatorHeader['tokens']` value in the `Auth.php` config file.
```suggestion
> By default, `$authenticatorHeader['tokens']` is set to `Authorization`. You can change the header name by setting the `$authenticatorHeader['tokens']` value in the `Auth.php` config file.
```

2022-09-19 10:38 UTC, MGatner commented on docs/guides/mobile_apps.md
> +> e.g. if `$authenticatorHeader['tokens']` is set to `PersonalAccessCodes`. the mobile client should return the raw token in the `PersonalAccessCodes` header as a `Bearer` token.
```suggestion
> e.g. if `$authenticatorHeader['tokens']` is set to `PersonalAccessCodes` then the mobile client should return the raw token in the `PersonalAccessCodes` header as a `Bearer` token.
```

2022-09-21 01:33 UTC, kenjis approved these changes

2022-09-21 10:17 UTC, MGatner approved these changes

2022-09-21 12:53 UTC, merged