Add filter permission and group
codeigniter4/shield pull request #535
Opened 2022-11-21 05:04 UTC by lonnieezell

Supersedes #393 

Provides new Groups/Permission filters.

Most of the original work was done by @jlopes90, I just tweaked the filters and added tests.

2022-11-23 09:48 UTC, kenjis commented
There is a conflict. Please rebase.
https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#updating-your-branch

2022-11-30 05:27 UTC, samsonasik commented on docs/authorization.md
> +
Typo: undeer -> under

2022-11-30 05:27 UTC, samsonasik commented on docs/authorization.md
> +
Protetection -> protection

2022-11-30 05:31 UTC, kenjis commented on docs/authorization.md
> +You can restrict access to multiple routes through a [Controller Filter](https://codeigniter.com/user_guide/incoming/filters.html). One is provided for both restricting via groups the user belongs to
```suggestion
You can restrict access to multiple routes through a [Controller Filter](https://codeigniter.com/user_guide/incoming/filters.html). One is provided for both restricting via groups the user belongs to, as well as which permission they need. The filters are automatically registered with the system under the `group` and `permission` aliases, respectively. You can define the protections within `app/Config/Filters.php`:
```

2022-11-30 05:32 UTC, lonnieezell commented
I rebased. Though it's giving me Rector fails now. If I fix the Rector issues then it becomes PHPStan issues since it doesn't know what type of variable it is, so I don't know how to please both, here. 

```
public function testFilterIncorrectGroupWithPrevious()
     {
-        /** @var User */
         $user = fake(UserModel::class);
         $user->addGroup('beta');
    ----------- end diff -----------

Applied rules:
 * RemoveNonExistingVarAnnotationRector (https://github.com/phpstan/phpstan/commit/d17e459fd9b45129c5deafe12bca56f30ea5ee99#diff-9f3541876405623b0d1[86](https://github.com/codeigniter4/shield/actions/runs/3580591390/jobs/6022847424#step:7:87)31259763dc1)
```

vs: 

```
------ ------------------------------------------------------- 
  Line   tests/Authentication/Filters/PermissionFilterTest.php  
 ------ ------------------------------------------------------- 
  :34    Cannot call method addPermission() on array|object.    
  :50    Cannot call method addPermission() on array|object.    
  :65    Cannot call method addPermission() on array|object.    
 ------ ------------------------------------------------------- 
```

2022-11-30 05:34 UTC, kenjis commented on tests/Authentication/Filters/GroupFilterTest.php
> +        /** @var User */
```suggestion
        /** @var User user */
```

2022-11-30 07:15 UTC, kenjis commented
Lang items are missing.

```
1) Tests\Language\TurkishTranslationTest::testAllConfiguredLanguageKeysAreIncluded with data set "tr" ('tr')
Failed asserting that the language key "Auth.notEnoughPrivilege" in the main repository is included for translation in "tr" locale.
Failed asserting that an array is empty.

/home/runner/work/shield/shield/tests/Language/AbstractTranslationTestCase.php:174

2) Tests\Language\ItalianTranslationTest::testAllConfiguredLanguageKeysAreIncluded with data set "it" ('it')
Failed asserting that the language key "Auth.notEnoughPrivilege" in the main repository is included for translation in "it" locale.
Failed asserting that an array is empty.

/home/runner/work/shield/shield/tests/Language/AbstractTranslationTestCase.php:174
```
https://github.com/codeigniter4/shield/actions/runs/3580771788/jobs/6023181104

2022-12-10 09:42 UTC, kenjis commented on tests/Authentication/Filters/PermissionFilterTest.php
> +        // Should redirect to home page since previous_url is not set
This is also not correct.

2022-12-10 18:37 UTC, lonnieezell commented on tests/Authentication/Filters/GroupFilterTest.php
> +        // Should redirect to home page since previous_url is not set
Done

2022-12-11 12:06 UTC, MGatner requested changes
Since really all that is different is the actually Auth check (`inGroup()` versus `can()`) can we make an abstract filter class that handles all the rest and just processes the arguments in a separate method?
```php
abstract protected function isAuthorized(array $arguments);
```

This would make a convenient starting point for developers making their own authorization filters as well.

2022-12-12 04:36 UTC, lonnieezell commented
@MGatner Good call. Done.

2022-12-12 11:57 UTC, MGatner approved these changes
Looks good for me! Maybe @kenjis or @datamweb could take one last look?

2022-12-12 22:32 UTC, datamweb commented on src/Filters/AbstractAuthFilter.php
> +            return redirect()->back()->with('error', lang('Auth.notEnoughPrivilege'));
I used this PR in a practical way. I did not see a problem.

What bothers me is displaying the **error message** to the user.
**Bonfire2** uses [Tatter/Alerts](https://github.com/tattersoftware/codeigniter4-alerts) to display errors, but the following code should be used to display errors on the shield:
```php
    <?php if (session('error') !== null) : ?>
        <div class="alert alert-danger" role="alert"><?= session('error') ?></div>
    <?php elseif (session('errors') !== null) : ?>
        <div class="alert alert-danger" role="alert">
            <?php if (is_array(session('errors'))) : ?>
                <?php foreach (session('errors') as $error) : ?>
                    <?= $error ?>
                    <br>
                <?php endforeach ?>
            <?php else : ?>
                <?= session('errors') ?>
            <?php endif ?>
        </div>
    <?php endif ?>
```

In fact, I'm not sure how Shield users should know what to do to display error message (`Auth.notEnoughPrivilege`). Perhaps the need to add an explanation in the documentation or something else.

2022-12-12 22:33 UTC, datamweb approved these changes
Thanks all.

2022-12-13 05:01 UTC, merged