Add returnLink to login view with localizations
codeigniter4/shield pull request #635
Opened 2023-02-14 07:08 UTC by evansharp

A convenience addition to the login view: a small link back to the base url. Useful especially after a logout if a custom redirect hasn't been defined.

Perhaps needs a setting to enable disable?

2023-02-14 08:05 UTC, datamweb commented
Thank you for sending this PR.

Please sign your commits:
https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#signing

Add test for your work:
https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#unit-testing

Replace the items as follows:
```php
'goToHome' => 'Go to home ➔',
```
```html
<p class="text-center"><a href="<?= base_url() ?>"><?= lang('Auth.goToHome') ?></a></p>
```

And add this feature to **Views\magic_link_message.php** as well.

2023-02-14 08:09 UTC, datamweb commented
> Perhaps needs a setting to enable disable?
No need.

2023-03-15 12:52 UTC, robsonpiere requested changes

2023-09-05 19:06 UTC, datamweb commented
I'm closing this one, due to lack of feedback, anyone can safely reopen it.

2023-09-05 19:06 UTC, closed without merging