[sr] Serbian Language translation
codeigniter4/shield pull request #676
Opened 2023-03-15 08:03 UTC by nebojsajsimic

2023-03-15 08:16 UTC, datamweb requested changes

2023-03-15 08:16 UTC, datamweb commented on src/Language/sr/Auth.php
> +    'emailIpAddress' => 'IP Address:',
How about?

2023-03-15 08:16 UTC, datamweb commented on src/Language/sr/Auth.php
> +    'successLogout'      => 'You have successfully logged out.',
How about?

2023-03-15 08:16 UTC, datamweb commented on tests/Language/AbstractTranslationTestCase.php
> +        SerbianTranslationTest::class  => 'sr',
```suggestion
        SerbianTranslationTest::class => 'sr',
```

2023-03-15 23:28 UTC, datamweb approved these changes
@nebojsajsimic Thank you for PRs.
Welcome to The Shield.

2023-03-16 01:52 UTC, kenjis approved these changes

2023-03-16 01:55 UTC, merged