Update to view templates
codeigniter4/shield pull request #89
Opened 2022-04-29 08:00 UTC by Sammyskills

1. Corrected the wrong route name used in the magic link email template which resulted in a blank url when sent.
2. Updated the magic link form response to display an error if a wrong or invalid email address is entered.

2022-04-29 13:09 UTC, MGatner requested changes
Looks good! You see to have mixed tabs and spaces in the view, quick change.

2022-04-29 13:09 UTC, MGatner commented on src/Views/magic_link_form.php
> +			<?php endif ?>
```suggestion
            
            <?php if (session('error') !== null) : ?>
            <div class="alert alert-danger" role="alert"><?= session('error') ?></div>
            <?php endif ?>
```

2022-04-29 13:30 UTC, MGatner approved these changes

2022-04-29 16:21 UTC, MGatner requested changes

2022-04-29 16:21 UTC, MGatner commented on src/Views/email_activate_email.php
> +<p>$code</p>
This should be echoed out. 
```suggestion
<p><?= $code ?></p>
```
But also: why the drastic change? Was the other solution not working?

2022-04-29 16:30 UTC, Sammyskills commented
Thanks for the correction.

Yes, the url from the email returns a 404 error. Moreover the `email_activate_show` form indicates the message below:

`We just sent an email to you with a code to confirm your email address. Copy that code and paste it below`

2022-04-29 17:25 UTC, MGatner approved these changes
Thanks for clarifying!

2022-04-30 04:47 UTC, merged

2022-04-30 08:36 UTC, kenjis commented
The test fails.
```
There was 1 failure:

1) Tests\Controllers\ActionsTest::testEmailActivateShow
Failed asserting that '<!-- DEBUG-VIEW START 1 /Users/kenji/work/codeigniter/codeigniter-shield/src/Views/email_activate_email.php -->\n
<p>Please use the code below to activate your account and start using the site.</p>\n
\n
<p>367129</p>\n
\n
<!-- DEBUG-VIEW ENDED 1 /Users/kenji/work/codeigniter/codeigniter-shield/src/Views/email_activate_email.php -->' contains "Please click the link below to activate your account".

.../codeigniter-shield/tests/Controllers/ActionsTest.php:220
```

2022-04-30 11:23 UTC, MGatner commented
You're right - tests/Controllers/ActionsTest.php L221 needs updating.

2022-05-01 03:03 UTC, kenjis commented
I sent a PR: #93